language: Python
python: 
  - "2.7"

install:
  - pip install flake8

env:
  - SCRIPT=cd search && echo ($pwd) && python tests.py
  - SCRIPT=flake8 --config=jenkins/flake8.ini search

script:
  - $SCRIPT
