language: Python
python: 
  - "2.7"

install:
  - pip install flake8

matrix:
  - include:
    - name: "Unit Tests"
      script: cd search && python tests.py
    - name: "Code Style"
      script: flake8 --config=jenkins/flake8.ini search
