dist: 'xenial'
language: Python
python: 
  - "2.7"

install:
  - pip install flake8

matrix:
  include:
  - env: SCRIPT='python tests.py'
    services:
    - xvfb
    before_script: 'cd search && export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3' # give xvfb some time to start
  - env: SCRIPT=flake8 --config=jenkins/flake8.ini search

script:
  - $SCRIPT
